version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf:1.21.3
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:9.2.5
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana-provisioning/:/etc/grafana/provisioning
      - ./grafana.ini:/etc/grafana/grafana.ini

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: 'ozono_db'
      INFLUXDB_ADMIN_USER: 'root'
      INFLUXDB_ADMIN_PASSWORD: 'root'
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
  
  mongodb:
    image:  mongo:5.0.9
    ports:
      - 27019:27017
    volumes:
      - ./mongoDB/dbData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd0438

volumes:
  mosquitto_data:
  mosquitto_logs:
  influxdb_data:
  grafana_data:
  dbData: